server:
  forward-headers-strategy: framework

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  flyway:
    baseline-on-migrate: false
    clean-disabled: true
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
  jackson:
    time-zone: Asia/Seoul
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          time_zone: UTC
    show-sql: false
  mail:
    host: smtp.gmail.com
    password: ${GMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${GMAIL}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  web:
    resources:
      add-mappings: false

app:
  s3:
    bucket: ${AWS_RESOURCE_BUCKET}
  auth:
    refresh-cookie:
      secure: ${REFRESH_COOKIE_SECURE:false}
      same-site: ${REFRESH_COOKIE_SAME_SITE:Lax}
      domain: ${REFRESH_COOKIE_DOMAIN:}
      path: /
    access-cookie:
      secure: ${ACCESS_COOKIE_SECURE:false}
      same-site: ${ACCESS_COOKIE_SAME_SITE:Lax}
      domain: ${ACCESS_COOKIE_DOMAIN:}
      path: /

google:
  client-id: ${GOOGLE_CLIENT_ID}

jwt:
  googleIssuer: ${GOOGLE_ISSUER}
  secretKey: ${SECRET_KEY}
  selfIssuer: ${SELF_ISSUER}
  audience: ${JWT_AUDIENCE}
  accessTokenValidity: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: off
