name: CD - DEV

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/gdgoc-be-app-dev:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gdgoc-be-app-dev:latest

      - name: Prepare appspec.yml (dev)
        run: cp appspec.dev.yml appspec.yml

      - name: Create Deployment Package
        run: |
          cat > .env <<EOF
          DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME_DEV=${{ secrets.DB_NAME_DEV }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_ISSUER=${{ secrets.GOOGLE_ISSUER }}
          SELF_ISSUER=${{ secrets.SELF_ISSUER }}
          JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
          REFRESH_COOKIE_SECURE=${{ secrets.REFRESH_COOKIE_SECURE || 'false' }}
          REFRESH_COOKIE_SAME_SITE=${{ secrets.REFRESH_COOKIE_SAME_SITE || 'Lax' }}
          REFRESH_COOKIE_DOMAIN=${{ secrets.REFRESH_COOKIE_DOMAIN }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_RESOURCE_BUCKET=${{ secrets.AWS_RESOURCE_BUCKET }}
          AWS_TEST_RESOURCE_BUCKET=${{ secrets.AWS_TEST_RESOURCE_BUCKET }}
          GMAIL=${{ secrets.GMAIL }}
          GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}
          DOZZLE_USERNAME=${{ secrets.DOZZLE_USERNAME }}
          DOZZLE_PASSWORD=${{ secrets.DOZZLE_PASSWORD }}
          EOF
        
          # 루트 기준 파일들만 압축
          zip -r deploy-dev.zip appspec.yml docker-compose-dev.yml deploy.dev.sh .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Deployment Package to S3
        run: aws s3 cp deploy-dev.zip s3://${{ secrets.AWS_S3_BUCKET }}/deploy-dev.zip

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "${{ secrets.AWS_CODEDEPLOY_APP }}" \
            --deployment-group-name "${{ secrets.AWS_CODEDEPLOY_GROUP_DEV }}" \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=deploy-dev.zip
